name: Run tests

on:
  pull_request:
    branches:
      - ci_test

jobs:
  build:
    runs-on: vitis

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Restoring build cache 
      uses: actions/cache@v2
      id: build-cache
      with:
        path: ${{ env.GITHUB_WORKSPACE }}/build
        key: build-cache
    - name: Configure build
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: python3 ${{ env.GITHUB_WORKSPACE }}/llvm/buildbot/configure.py
    - name: Build compiler
      run: python3 ${{ env.GITHUB_WORKSPACE }}/llvm/buildbot/compile.py
    - name: Creating artifact for builded compiler
      uses: actions/upload-artifact@v2
      with:
        name: sycl-compiler
        path: ${{ env.GITHUB_WORKSPACE }}/build

