name: Run tests

on:
  pull_request:
    branches:
      - ci_test

jobs:
  build:
    runs-on: sycl-vxx-env

    steps:
    - name: Clean source volume if it exists
      run: docker volume rm sycl_ci_sources
    - name: Check out repository code
      run: docker run --rm --volume sycl_ci_sources:/sycl_ci_sources alpine/git clone --depth=1 --branch ${{ github.ref }} ${{ github.repository }} /sycl_ci_sources
      if: succeeded() || failed()
    - name: Configure build
      run: docker run --rm --volume sycl_ci_sources:/sycl_ci_sources sycl-vxx-build python3 /sycl_ci_sources/buildbot/configure.py --no-werror
    - name: Build compiler
      run: docker run --rm --volume sycl_ci_sources:/sycl_ci_sources sycl-vxx-build python3 /sycl_ci_sources/buildbot/compile.py
    - name: Run tests
      run: docker run --rm --volume sycl_ci_sources:/sycl_ci_sources sycl-vxx-runenv cmake --build /sycl_ci_sources/build --target check-sycl-xocc-j2

